// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVnjsvLBBJJGqPVYdvWzWCDbtUMamdMlE',
    appId: '1:15598088629:web:857af4a34d21ca8c42e9fc',
    messagingSenderId: '15598088629',
    projectId: 'lapakbantull-50da5',
    authDomain: 'lapakbantull-50da5.firebaseapp.com',
    storageBucket: 'lapakbantull-50da5.firebasestorage.app',
    measurementId: 'G-FXYEZEKB9M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKg7ZBJoJ9UJ2fSNVq_8F8X3errB4jT-4',
    appId: '1:15598088629:android:1a9ebd10ec7c8aba42e9fc',
    messagingSenderId: '15598088629',
    projectId: 'lapakbantull-50da5',
    storageBucket: 'lapakbantull-50da5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxY_M8ds6s_iFESDKnALX022m1mXV4Q64',
    appId: '1:15598088629:ios:706502d644360a7f42e9fc',
    messagingSenderId: '15598088629',
    projectId: 'lapakbantull-50da5',
    storageBucket: 'lapakbantull-50da5.firebasestorage.app',
    iosBundleId: 'com.example.lapakbantull',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxY_M8ds6s_iFESDKnALX022m1mXV4Q64',
    appId: '1:15598088629:ios:706502d644360a7f42e9fc',
    messagingSenderId: '15598088629',
    projectId: 'lapakbantull-50da5',
    storageBucket: 'lapakbantull-50da5.firebasestorage.app',
    iosBundleId: 'com.example.lapakbantull',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVnjsvLBBJJGqPVYdvWzWCDbtUMamdMlE',
    appId: '1:15598088629:web:ede84a70a858dc2e42e9fc',
    messagingSenderId: '15598088629',
    projectId: 'lapakbantull-50da5',
    authDomain: 'lapakbantull-50da5.firebaseapp.com',
    storageBucket: 'lapakbantull-50da5.firebasestorage.app',
    measurementId: 'G-5JRSMKYR6Q',
  );
}
